[2021-10-29 00:54:55] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 00:54:55] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":86,"packet_sent":57,"packet_lost":0,"message_received":21,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1635440091}},"time":1635440093}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 00:54:59] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:56:34] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:57:20] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:57:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 00:57:30] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":117,"packet_sent":85,"packet_lost":0,"message_received":24,"message_sent":3,"disconnect_times":1,"lost_times":0,"last_message_time":1635440243}},"time":1635440248}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 00:57:35] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 00:57:35] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":119,"packet_sent":87,"packet_lost":0,"message_received":24,"message_sent":3,"disconnect_times":1,"lost_times":0,"last_message_time":1635440243}},"time":1635440253}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 00:57:40] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 00:57:40] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":119,"packet_sent":87,"packet_lost":0,"message_received":24,"message_sent":3,"disconnect_times":1,"lost_times":0,"last_message_time":1635440243}},"time":1635440258}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 00:57:41] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:58:04] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:58:14] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:58:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 00:58:20] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":132,"packet_sent":99,"packet_lost":0,"message_received":25,"message_sent":6,"disconnect_times":1,"lost_times":0,"last_message_time":1635440264}},"time":1635440298}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 00:58:23] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 00:59:37] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 00:59:51] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:00:08] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:00:20] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:00:57] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:01:25] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:01:53] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:05:07] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:05:22] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:14:06] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:18:28] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:18:34] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:29:15] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:29:15] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":401,"packet_sent":244,"packet_lost":0,"message_received":106,"message_sent":51,"disconnect_times":1,"lost_times":0,"last_message_time":1635441585}},"time":1635442153}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:29:18] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:29:30] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:30:07] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:30:25] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:30:37] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:31:00] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:31:09] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:31:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:31:30] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":417,"packet_sent":252,"packet_lost":0,"message_received":113,"message_sent":55,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442288}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:31:35] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:31:35] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":419,"packet_sent":254,"packet_lost":0,"message_received":113,"message_sent":55,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442293}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:31:40] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:31:40] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":419,"packet_sent":254,"packet_lost":0,"message_received":113,"message_sent":55,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442298}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:31:45] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:31:45] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":419,"packet_sent":254,"packet_lost":0,"message_received":113,"message_sent":55,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442303}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:31:49] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:31:55] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:31:55] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":420,"packet_sent":255,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442313}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:00] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:00] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":420,"packet_sent":255,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442318}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:05] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442323}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:10] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442328}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:15] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:15] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442333}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:20] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442338}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:25] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:25] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442343}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:30] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":421,"packet_sent":256,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442348}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:35] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:35] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442353}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:40] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:40] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442358}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:45] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:45] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442363}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:50] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:50] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442368}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:32:55] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:32:55] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442373}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:00] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:33:00] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":422,"packet_sent":257,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442378}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:33:05] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":423,"packet_sent":258,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442383}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:33:10] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":423,"packet_sent":258,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442388}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:15] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:33:15] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":423,"packet_sent":258,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442393}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:33:20] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":423,"packet_sent":258,"packet_lost":0,"message_received":113,"message_sent":56,"disconnect_times":1,"lost_times":0,"last_message_time":1635442287}},"time":1635442398}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:33:22] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:33:27] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:33:48] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:33:52] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:34:02] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:34:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:34:10] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":430,"packet_sent":263,"packet_lost":0,"message_received":115,"message_sent":59,"disconnect_times":1,"lost_times":0,"last_message_time":1635442431}},"time":1635442448}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:34:13] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:35:18] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:35:54] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:35:58] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:36:18] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:36:36] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:36:42] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:36:53] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:36:58] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 01:38:55] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:40:00] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:53:59] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:57:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:57:10] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":563,"packet_sent":361,"packet_lost":0,"message_received":132,"message_sent":75,"disconnect_times":1,"lost_times":0,"last_message_time":1635443661}},"time":1635443828}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:57:11] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:58:11] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:58:36] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 01:59:25] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 01:59:25] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":583,"packet_sent":372,"packet_lost":0,"message_received":137,"message_sent":82,"disconnect_times":1,"lost_times":0,"last_message_time":1635443941}},"time":1635443963}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 01:59:26] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 02:03:25] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:03:25] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":597,"packet_sent":384,"packet_lost":0,"message_received":138,"message_sent":84,"disconnect_times":1,"lost_times":0,"last_message_time":1635443972}},"time":1635444203}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:03:28] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 02:05:10] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 02:05:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:30] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":610,"packet_sent":392,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444328}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:05:35] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:35] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":610,"packet_sent":392,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444333}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:05:40] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:40] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444338}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:05:45] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:45] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444343}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:05:50] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:50] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444348}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:05:55] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:05:55] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444353}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:00] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:00] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444358}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:05] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":611,"packet_sent":393,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444363}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:10] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":612,"packet_sent":394,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444368}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:15] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:15] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":612,"packet_sent":394,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444373}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:20] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":612,"packet_sent":394,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444378}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:25] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:25] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":612,"packet_sent":394,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444383}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-10-29 02:06:30] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":1634871401,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":612,"packet_sent":394,"packet_lost":0,"message_received":141,"message_sent":88,"disconnect_times":1,"lost_times":0,"last_message_time":1635444325}},"time":1635444388}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-10-29 02:06:31] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 02:07:38] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 12:38:04] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:38:18] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:40:37] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:41:01] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:42:16] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:42:22] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:42:39] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:44:12] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:44:17] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:46:37] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:46:54] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:47:46] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:50:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": read tcp 127.0.0.1:2687->127.0.0.1:5701: wsarecv: An existing connection was forcibly closed by the remote host. 将重试. 
[2021-10-29 12:50:05] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":300750966,"message":"[CQ:at,qq=1634871401] en:  庆历四年春，滕子京谪守巴陵郡。越明年，政通人和，百废具兴，乃重修岳阳楼，增其旧制，刻唐贤今人诗赋于其上，属予作文以记之。\r\n\r\n予观夫巴陵胜状，在洞庭一湖。衔远山，吞长江，浩浩汤汤，横无际涯，朝晖夕阴，气象万千，此则岳阳楼之大观也，前人之述备矣。然则北通巫峡，南极潇湘，迁客骚人，多会于此，览物之情，得无异乎？","message_id":-1757575774,"message_seq":4296,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=1634871401] en:  庆历四年春，滕子京谪守巴陵郡。越明年，政通人和，百废具兴，乃重修岳阳楼，增其旧制，刻唐贤今人诗赋于其上，属予作文以记之。\r\n\r\n予观夫巴陵胜状，在洞庭一湖。衔远山，吞长江，浩浩汤汤，横无际涯，朝晖夕阴，气象万千，此则岳阳楼之大观也，前人之述备矣。然则北通巫峡，南极潇湘，迁客骚人，多会于此，览物之情，得无异乎？","self_id":1634871401,"sender":{"age":0,"area":"","card":"西大 胖头鱼","level":"","nickname":"～(z_z)","role":"admin","sex":"unknown","title":"群学姐","user_id":3346017377},"sub_type":"normal","time":1635483008,"user_id":3346017377}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": read tcp 127.0.0.1:2687->127.0.0.1:5701: wsarecv: An existing connection was forcibly closed by the remote host. 
[2021-10-29 12:50:42] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:53:34] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 12:53:43] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:54:13] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 12:54:38] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:55:39] [WARNING]: 转换CQ码 [CQ:record,file=B0550C9E5430F3F93E68E7FA032851D3.silk] 时出现错误: syntax error 将原样发送. 
[2021-10-29 12:55:57] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:56:36] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:56:38] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:56:43] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:57:01] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:57:11] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 12:59:08] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:01:51] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:02:03] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:04:29] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:09:38] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:09:58] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:10:06] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:10:23] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:10:28] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":300750966,"message":"[CQ:video,file=f6b1cf7f199627a20c6824a5a6c6e800.video,url=http://120.221.168.57:80/qqdownload?ver=537065739\u0026amp;rkey=3081fd0201010481f53081f20201010201000204617228690481a6333035313032303130303034333633303334303230313030303230346337373032633631303230333761316166663032303439306435333036663032303436313762383232613034313066366231636637663139393632376132306336383234613561366336653830303032303337613164626230323031303030343134303030303030303836363639366336353734373937303635303030303030303433313330333033330204617b823904350000000866696c657479706500000004313030330000000b646f776e656e63727970740000000130000000047175696300000001300400\u0026amp;filetype=1003\u0026amp;videotype=1\u0026amp;subvideotype=0\u0026amp;term=unknow]","message_id":1664079177,"message_seq":4467,"message_type":"group","post_type":"message","raw_message":"[CQ:video,file=f6b1cf7f199627a20c6824a5a6c6e800.video]","self_id":1634871401,"sender":{"age":0,"area":"","card":"西大 胖头鱼","level":"","nickname":"～(z_z)","role":"admin","sex":"unknown","title":"群学姐","user_id":3346017377},"sub_type":"normal","time":1635484230,"user_id":3346017377}
 到 127.0.0.1:5701 失败: read tcp 127.0.0.1:1685->127.0.0.1:5701: wsarecv: An existing connection was forcibly closed by the remote host. 
[2021-10-29 13:10:58] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:10:59] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:11:01] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:11:36] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:12:06] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:12:09] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:12:10] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:12:13] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:15:04] [WARNING]: 群消息发送失败: 信息为空. 
[2021-10-29 13:30:45] [WARNING]: 群消息发送失败: 信息为空. 
